-- mcp_metric_staging.sql
-- Creates the DBX_MONITOR schema and metric staging table.
-- Run as SYS or a user with CREATE USER + GRANT privileges.

CREATE USER DBX_MONITOR IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
  QUOTA 1G ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE JOB TO DBX_MONITOR;
GRANT SELECT ON V_$SESSION TO DBX_MONITOR;
GRANT SELECT ON V_$SYSTEM_EVENT TO DBX_MONITOR;
GRANT SELECT ON V_$SYSSTAT TO DBX_MONITOR;
GRANT SELECT ON V_$SGA TO DBX_MONITOR;
GRANT SELECT ON V_$PGASTAT TO DBX_MONITOR;
GRANT SELECT ON V_$LOG TO DBX_MONITOR;
GRANT SELECT ON V_$LOG_HISTORY TO DBX_MONITOR;
GRANT SELECT ON V_$UNDOSTAT TO DBX_MONITOR;
GRANT SELECT ON V_$PARAMETER TO DBX_MONITOR;
GRANT SELECT ON DBA_TABLESPACE_USAGE_METRICS TO DBX_MONITOR;

CREATE TABLE DBX_MONITOR.MCP_METRIC_STAGING (
    metric_name   VARCHAR2(128)  NOT NULL,
    metric_value  NUMBER         NOT NULL,
    labels        VARCHAR2(4000) DEFAULT '{}',
    collected_at  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY RANGE (collected_at)
  INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
  (PARTITION p_initial VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'));

CREATE INDEX DBX_MONITOR.IDX_STAGING_TIME
  ON DBX_MONITOR.MCP_METRIC_STAGING (collected_at DESC) LOCAL;
